export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  VERIFY_OTP = 'VERIFY_OTP',
  RESEND_OTP = 'RESEND_OTP',
  OAUTH_LOGIN = 'OAUTH_LOGIN',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
